//Sam Ballard

package lab3;
import java.util.Scanner;
public class PersonTest {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		String name, address, email, phone, year, salary, dateHired, officeHours, rank, title;
		boolean office;
		System.out.println("Person 1");
		System.out.println("Enter person's name: ");
		name = sc.nextLine();
		System.out.println("Enter person's address: ");
		address = sc.nextLine();
		System.out.println("Enter person's email: ");
		email = sc.nextLine();
		System.out.println("Enter person's phone number: ");
		phone = sc.nextLine();
		Person homo = new Person(name, address, email, phone);
		System.out.println("Person 2, Student");
		System.out.println("Enter person's name: ");
		name = sc.nextLine();
		System.out.println("Enter person's address: ");
		address = sc.nextLine();
		System.out.println("Enter person's email: ");
		email = sc.nextLine();
		System.out.println("Enter person's phone number: ");
		phone = sc.nextLine();
		System.out.println("Enter student's year: ");
		year = sc.nextLine();
		Student homo1 = new Student(name, address, email, phone, year);
		System.out.println("Person 3, Employee");
		System.out.println("Enter person's name: ");
		name = sc.nextLine();
		System.out.println("Enter person's address: ");
		address = sc.nextLine();
		System.out.println("Enter person's email: ");
		email = sc.nextLine();
		System.out.println("Enter person's phone number: ");
		phone = sc.nextLine();
		System.out.println("Does employee have an office? (True/False): ");
		office = sc.nextBoolean();
		sc.nextLine();
		System.out.println("Enter the employee's salary: ");
		salary = sc.nextLine();
		System.out.println("Enter the employees date of hire");
		dateHired = sc.nextLine();
		Employee homo2 = new Employee(name, address, email, phone, office, salary, dateHired);
		System.out.println("Person 4, Employee 2, Faculty");
		System.out.println("Enter person's name: ");
		name = sc.nextLine();
		System.out.println("Enter person's address: ");
		address = sc.nextLine();
		System.out.println("Enter person's email: ");
		email = sc.nextLine();
		System.out.println("Enter person's phone number: ");
		phone = sc.nextLine();
		System.out.println("Does employee have an office? (True/False): ");
		office = sc.nextBoolean();
		sc.nextLine();
		System.out.println("Enter the employee's salary: ");
		salary = sc.nextLine();
		System.out.println("Enter the employees date of hire");
		dateHired = sc.nextLine();
		System.out.println("Enter the faculty member's office hours: ");
		officeHours = sc.nextLine();
		System.out.println("Enter the faculty member's rank: ");
		rank = sc.nextLine();
		Faculty homo3 = new Faculty(name, address, email, phone, office, salary, dateHired, officeHours, rank);
		System.out.println("Person 5, Employee 3, Staff");
		System.out.println("Enter person's name: ");
		name = sc.nextLine();
		System.out.println("Enter person's address: ");
		address = sc.nextLine();
		System.out.println("Enter person's email: ");
		email = sc.nextLine();
		System.out.println("Enter person's phone number: ");
		phone = sc.nextLine();
		System.out.println("Does employee have an office? (True/False): ");
		office = sc.nextBoolean();
		sc.nextLine();
		System.out.println("Enter the employee's salary: ");
		salary = sc.nextLine();
		System.out.println("Enter the employees date of hire");
		dateHired = sc.nextLine();
		System.out.println("Enter staff member's title: ");
		title = sc.nextLine();
		Staff homo4 = new Staff(name, address, email, phone, office, salary, dateHired, title);
		System.out.println(homo.toString());
		System.out.println(homo1.toString());
		System.out.println(homo2.toString());
		System.out.println(homo3.toString());
		System.out.println(homo4.toString());
		sc.close();
	}
}
